name: Build and push container images

on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"

env:
  REGISTRY: ghcr.io
  AGENT_IMAGE_NAME: ${{ github.repository }}
  IMAGE_DESCRIPTION: ${{ github.repository }} container for use with Mythic
  IMAGE_SOURCE: ${{ github.server_url }}/${{ github.repository }}
  IMAGE_LICENSE: BSD-3-Clause
  VERSION: ${{ github.ref_name }}

jobs:
  agent_build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: 'arm64,arm'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Lowercase the server container image name
        run: echo "AGENT_IMAGE_NAME=${AGENT_IMAGE_NAME,,}" >> ${GITHUB_ENV}

      - name: Build and push the server container image
        uses: docker/build-push-action@v6
        with:
          context: Payload_Type/xenon
          file: Payload_Type/xenon/Dockerfile
          tags: |
            ${{ env.REGISTRY }}/${{ env.AGENT_IMAGE_NAME }}:${{ env.VERSION }}
            ${{ env.REGISTRY }}/${{ env.AGENT_IMAGE_NAME }}:latest
          push: true
          labels: |
            org.opencontainers.image.source=${{ env.IMAGE_SOURCE }}
            org.opencontainers.image.description=${{ env.IMAGE_DESCRIPTION }}
            org.opencontainers.image.licenses=${{ env.IMAGE_LICENSE }}
          platforms: linux/amd64,linux/arm64
